### ISSUE TITLE
Support for custom post types

### ISSUE THREAD

**Issue by nasyrov** [humanmade/HM-Related-Posts#18]
Hi @roborourke ,

What do you think about adding a filter here to support custom post types?

https://github.com/humanmade/HM-Related-Posts/blob/385cd8a47e7766447f0b6f641f695a11d9e0361b/inc/admin/namespace.php#L24

Cheers,

**Comment by roborourke** [comment]
Yep, that’s a good addition. Surprised we didn’t already do that to be
honest!

Will probably implement it using `add_post_type_support()`. More
straightforward than a filter I think

**Comment by roborourke** [comment]
@nasyrov that'd be fantastic if you have time to do it!

**Comment by nasyrov** [comment]
Hi @roborourke,

Could you please review the pull request?

Thanks,
E

**Comment by roborourke** [comment]
Tagged & released v1.2.2

Cheers!

**Comment by nasyrov** [comment]
Thank you!
